"""Regenerate sleight_of_hand/holdem/preflop_tables.py.

Heads-up all-in equity for each of the 169 starting-hand classes, measured
with the repository's own evaluator over full five-card runouts:

* against one uniformly random hand, which also defines the strength order;
* against the top X% of combinations in that order, X = 5, 10, ..., 100,
  used to evaluate calls against a shove from a non-random range.

Every (class, range) cell uses its own string-seeded generator, so output
is identical across runs and worker counts. Hero combinations rotate over
all of the class's suit combinations so card removal is averaged.
"""

from __future__ import annotations

import argparse
import random
import sys
from concurrent.futures import ProcessPoolExecutor
from itertools import accumulate
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sleight_of_hand.holdem.equity import DECK, rank_hand
from sleight_of_hand.holdem.hands import (
    CLASSES,
    COMBOS,
    TOTAL_COMBOS,
    class_combos,
)

OUTPUT = ROOT / "sleight_of_hand" / "holdem" / "preflop_tables.py"
WIDTHS = tuple(range(5, 101, 5))


def top_range(order: list[str], width: int) -> list[tuple[tuple[int, int], float]]:
    """Weighted combos in the strongest ``width`` percent of all combos.

    The boundary class is included fractionally so the range is exact.
    """
    budget = TOTAL_COMBOS * width / 100
    weighted = []
    for label in order:
        if budget <= 0:
            break
        share = min(1.0, budget / COMBOS[label])
        weighted += [(combo, share) for combo in class_combos(label)]
        budget -= COMBOS[label]
    return weighted


def equity(
    label: str,
    villain: list[tuple[tuple[int, int], float]] | None,
    samples: int,
    tag: str,
) -> float:
    """Showdown share of ``label`` against ``villain`` (None means random)."""
    rng = random.Random(f"{label}:{tag}")
    heroes = class_combos(label)
    choices = []
    for hero in heroes:
        if villain is None:
            choices.append(None)
            continue
        live = [(c, w) for c, w in villain if not set(c) & set(hero)]
        choices.append(([c for c, _ in live], list(accumulate(w for _, w in live))))
    share = 0.0
    for i in range(samples):
        hero = heroes[i % len(heroes)]
        pick = choices[i % len(heroes)]
        if pick is None:
            deck = [c for c in DECK if c not in hero]
            dealt = rng.sample(deck, 7)
            opp, board = dealt[:2], dealt[2:]
        else:
            opp = rng.choices(pick[0], cum_weights=pick[1])[0]
            deck = [c for c in DECK if c not in hero and c not in opp]
            board = rng.sample(deck, 5)
        ours = rank_hand([*hero, *board])
        theirs = rank_hand([*opp, *board])
        share += 1.0 if ours > theirs else 0.5 if ours == theirs else 0.0
    return share / samples


def _random_cell(args: tuple[str, int]) -> tuple[str, float]:
    label, samples = args
    return label, equity(label, None, samples, "random")


def _range_cell(args: tuple[str, list[str], int, int]) -> tuple[str, int, float]:
    label, order, width, samples = args
    return label, width, equity(label, top_range(order, width), samples, f"top{width}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--random-samples", type=int, default=40000)
    parser.add_argument("--range-samples", type=int, default=6000)
    parser.add_argument("--workers", type=int, default=None)
    args = parser.parse_args()

    with ProcessPoolExecutor(args.workers) as pool:
        vs_random = dict(
            pool.map(_random_cell, [(c, args.random_samples) for c in CLASSES])
        )
        order = sorted(CLASSES, key=lambda c: (-vs_random[c], CLASSES.index(c)))
        jobs = [(c, order, w, args.range_samples) for c in CLASSES for w in WIDTHS]
        vs_top = {c: {100: vs_random[c]} for c in CLASSES}
        for label, width, value in pool.map(_range_cell, jobs, chunksize=8):
            if width != 100:
                vs_top[label][width] = value

    rows = "\n".join(
        f'    "{c}": "{" ".join(str(round(vs_top[c][w] * 10000)) for w in WIDTHS)}",'
        for c in order
    )
    OUTPUT.write_text(
        f'''"""Generated by scripts/generate_preflop_tables.py; do not edit by hand.

Heads-up all-in showdown equity per starting-hand class, from the repo's
own evaluator: {args.random_samples} samples against a random hand and
{args.range_samples} against each top-X% range (X = {WIDTHS[0]}..{WIDTHS[-1]}
by {WIDTHS[1] - WIDTHS[0]}). Values are basis points. Rows are listed in
strength order: descending equity against a random hand. These are measured
equities, not solver or Nash strategies.
"""

WIDTHS: tuple[int, ...] = tuple(range({WIDTHS[0]}, {WIDTHS[-1] + 1}, {WIDTHS[1] - WIDTHS[0]}))

_ROWS: dict[str, str] = {{
{rows}
}}

#: Class labels, strongest first by equity against a random hand.
ORDER: tuple[str, ...] = tuple(_ROWS)

#: ``EQUITY_VS_TOP[label][i]`` is equity against the top ``WIDTHS[i]`` percent.
EQUITY_VS_TOP: dict[str, tuple[float, ...]] = {{
    label: tuple(int(v) / 10000 for v in row.split()) for label, row in _ROWS.items()
}}

EQUITY_VS_RANDOM: dict[str, float] = {{
    label: row[-1] for label, row in EQUITY_VS_TOP.items()
}}
'''
    )
    print(OUTPUT)


if __name__ == "__main__":
    main()
